export interface ShareholderModel {
  _id: string,
  typeDocument: string,
  document: string,
  name: string,
  email: string,
  mobileNumber: string,
  phoneNumber: string,
  annexed: string,
  birthDate: string,
  address: string,
  createdAt: any,
  updatedAt: any,
  userId: string,
  businessId: string,
}
