export enum ConstructionPdfTypes {
  DOCUMENT = 'DOCUMENT',
  COMPLETION = 'COMPLETION',
  PARTNERSHIP = 'PARTNERSHIP',
  CONSTRUCTION = 'CONSTRUCTION',
  VOUCHER = 'VOUCHER',
  LEGAL = 'LEGAL',
  PRO = 'PRO',
}